image: 
  file:  .gitpod.Dockerfile

tasks:
  - name: start
    before: |
      pyenv virtualenv flvenv
      source activate flvenv

      export FLASK_APP = app
      export FLASK_ENV = development
      
      pip install flask
  - init: echo 'init script'   


# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# tasks:
#   - init: echo 'init script' # runs during prebuild
#     command: echo 'start script'

# # List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
