image: 
  file:  .gitpod.Dockerfile

tasks:
  # - name: start
- before: |
    pyenv virtualenv flvenv
    source activate flvenv

    export FLASK_APP=learnflask
    export FLASK_ENV=development
      
    pip install flask
    pip install flask-debugtoolbar
  init:  |
    echo "проверка init"
    #   source activate flvenv
    #   pip install Flask  

  command: flask run

ports:
  - port: 5000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - samuelcolvin.jinjahtml
